version: "3.9"
services:
  app:
    build: .
    container_name: nextjs_app
    restart: always
    env_file: .env.production
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "7"
